INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (2, N'BMW')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (4, N'Mercedes-Benz')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (6, N'Audi')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (8, N'Range Rover')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (10, N'Porsche')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (12, N'Ford')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (14, N'Honda')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (16, N'Hyundai')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (18, N'Kia')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (20, N'Land Rover')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (22, N'Lincoln')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (24, N'Renault')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (26, N'Lamborghini')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (28, N'Opel')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (30, N'Mini')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (32, N'Rolls Royce')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (34, N'Seat')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (36, N'Suzuki')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (38, N'Skoda')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (40, N'Toyota')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (42, N'Volkswagen')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (44, N'Volvo')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (46, N'Tofaş')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (48, N'Jeep')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (50, N'Isuzu')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (52, N'Iveco')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (54, N'Jaguar')
INSERT INTO [dbo].[Brands] ([BrandId], [BrandName]) VALUES (56, N'Fiat')
