INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (1, N'Red')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (3, N'Yellow')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (5, N'Blue')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (7, N'Black')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (9, N'White')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (11, N'Green')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (13, N'Grey')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (15, N'Dark Blue')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (17, N'Matte Black')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (19, N'Navy Blue')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (21, N'Burgundy')
INSERT INTO [dbo].[Colors] ([ColorId], [ColorName]) VALUES (23, N'Smoked')
