INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (10, N'Öztürk')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (15, N'Gallery''s')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (18, N'Beyzade')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (13, N'Arslan')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (19, N'Koç ')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (14, N'Bulut')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (11, N'Melek')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (12, N'Dilek')
INSERT INTO [dbo].[Customers] ([UserId], [CompanyName]) VALUES (17, N'Hüsrev')
