INSERT INTO [dbo].[Users] ([UserId], [FirstName], [LastName], [Email], [Password]) VALUES (10, N'Sema', N'Dilek', N'semadilek@hotmail.com', N'123')
INSERT INTO [dbo].[Users] ([UserId], [FirstName], [LastName], [Email], [Password]) VALUES (11, N'Merve', N'Deniz', N'mervedeniz@gmail.com', N'234')
INSERT INTO [dbo].[Users] ([UserId], [FirstName], [LastName], [Email], [Password]) VALUES (13, N'Kaan ', N'Gültekin', N'kaangültekin@hotmail.com', N'345')
INSERT INTO [dbo].[Users] ([UserId], [FirstName], [LastName], [Email], [Password]) VALUES (14, N'Tarık', N'Pamuk', N'tarıkpamuk@hotmail.com', N'567')
INSERT INTO [dbo].[Users] ([UserId], [FirstName], [LastName], [Email], [Password]) VALUES (15, N'Umay', N'Bilek', N'umaybilek@gmail.com', N'678')
INSERT INTO [dbo].[Users] ([UserId], [FirstName], [LastName], [Email], [Password]) VALUES (16, N'Tarık', N'Akın', N'tarıkakın@hotmail.com', N'789')
